import type { RepositoryFile } from "../models/file.js";
import type { RepositoryIndex } from "../models/repository-index.js";

export function generateLanguages(
  index: RepositoryIndex
): RepositoryFile[] {

  return Object.entries(index.languages).map(([language, problems]) => ({

    path: `languages/${language}.md`,

    content: [
      `# ${language}`,
      "",
      "| Problem |",
      "| ------- |",
      ...problems.map(problem => `| ${problem} |`),
      "",
      "---",
      "",
      "Generated by LeetSync",
    ].join("\n"),

  }));

}