import type { RepositoryFile } from "../models/file.js";
import type { RepositoryIndex } from "../models/repository-index.js";

export function generateRootReadme(
  index: RepositoryIndex
): RepositoryFile {

  return {

    path: "README.md",

    content: `# LeetCode Solutions

Automatically synced using **LeetSync**.

## Statistics

- Total Solved: ${index.totalSolved}
- Easy: ${index.easy}
- Medium: ${index.medium}
- Hard: ${index.hard}

---

Generated by LeetSync
`,

  };

}