import type { RepositoryFile } from "../models/file.js";
import type { RepositoryIndex } from "../models/repository-index.js";

export function generateTopics(
  index: RepositoryIndex
): RepositoryFile[] {

  return Object.entries(index.topics).map(([topic, problems]) => ({

    path: `topics/${topic}.md`,

    content: [
      `# ${topic}`,
      "",
      "| Problem |",
      "| ------- |",
      ...problems.map(problem => `| ${problem} |`),
      "",
      "---",
      "",
      "Generated by LeetSync",
    ].join("\n"),

  }));

}