import { readFile, syncFile } from "./file.service.js";

import type { SyncFileRequest } from "./file.types.js";
import type { RepositoryStats } from "./stats.service.js";

async function getStats(
  request: SyncFileRequest
): Promise<RepositoryStats> {
  const content = await readFile({
    ...request,
    path: "stats.json",
  });

  if (!content) {
    return {
      totalSolved: 0,
      easy: 0,
      medium: 0,
      hard: 0,
    };
  }

  return JSON.parse(content);
}

export async function updateReadme(
  request: SyncFileRequest
): Promise<void> {

  const stats = await getStats(request);

  const markdown = `# LeetCode Solutions

Automatically synced using **LeetSync**.

## Statistics

- Total Solved: ${stats.totalSolved}
- Easy: ${stats.easy}
- Medium: ${stats.medium}
- Hard: ${stats.hard}

---

Generated by LeetSync
`;

  await syncFile({
    ...request,
    path: "README.md",
    message: "Update repository README",
    content: markdown,
  });
}